const expectedGardenTitle=JSON.parse(readFileSync(new URL('../../community/world.json',import.meta.url),'utf8')).accepted.length>1?'A garden made together':'A little welcome';
import {readFileSync} from 'node:fs';
import {test,expect} from '@playwright/test';
for(const [name,width,height,touch]of [['desktop',1440,1000,false],['phone',375,667,true]]){
  test(`${name}: garden visits keep the shared mood unchanged`,async({browser})=>{
    const context=await browser.newContext({viewport:{width,height},hasTouch:touch,reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.route('**/status.json',route=>route.fulfill({json:{schemaVersion:1,state:'focused',revision:9,updatedAt:'2026-09-30T10:00:00Z'}}));
    await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-scene-ready','true');await expect(page.locator('#garden-button')).toBeVisible();const before=await page.locator('#updated-at').innerText();
    for(let i=0;i<2;i++){await page.locator('#garden-button').click();await expect(page.locator('#scene')).toHaveAttribute('data-view','garden');await expect(page.locator('#garden-note')).toBeVisible();await expect(page.locator('#gift-title')).toHaveText(expectedGardenTitle);await expect(page.locator('body')).toHaveAttribute('data-state','focused');await expect(page.locator('#updated-at')).toHaveText(before);await page.locator('#reset-button').click();await page.locator('#scene').focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('Home');if(!i)await page.screenshot({path:`qa/garden-${name}.png`,fullPage:true});await page.locator('#garden-button').click();await expect(page.locator('#scene')).toHaveAttribute('data-view','workshop');}
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const box=await page.locator('#garden-button').boundingBox();expect(box.height).toBeGreaterThanOrEqual(43.999);expect(errors).toEqual([]);await context.close();
  });
}
test('garden still view works without WebGL and returns to the mood image',async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(String(type).includes('webgl'))return null;return original.call(this,type,...args);};});const page=await context.newPage();await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-scene-ready','fallback');await page.locator('#garden-button').click();await expect(page.locator('#garden-fallback')).toBeVisible();await expect(page.locator('#scene-fallback')).toBeHidden();await page.screenshot({path:'qa/garden-fallback.png',fullPage:true});await page.locator('#garden-button').click();await expect(page.locator('#scene-fallback')).toBeVisible();await expect(page.locator('#garden-fallback')).toBeHidden();await context.close();});
test('losing WebGL in the garden keeps the selected still view and disables dead camera controls',async({page})=>{await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-scene-ready','true');await page.locator('#garden-button').click();await page.locator('.workshop-canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2')||canvas.getContext('webgl');const loss=gl?.getExtension('WEBGL_lose_context');if(!loss)throw new Error('Context-loss testing is unavailable');loss.loseContext();});await expect(page.locator('body')).toHaveAttribute('data-scene-ready','fallback');await expect(page.locator('#garden-fallback')).toBeVisible();await expect(page.locator('.workshop-canvas')).toBeHidden();await expect(page.locator('#motion-button')).toBeDisabled();await expect(page.locator('#reset-button')).toBeDisabled();await page.locator('#garden-button').click();await expect(page.locator('#scene-fallback')).toBeVisible();});
